# Generated by Django 4.2.6 on 2025-04-18 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0003_attraction_cover_image_destination_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название интереса')),
                ('slug', models.SlugField(help_text='Короткое имя для URL (например, history, food)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тег интереса',
                'verbose_name_plural': 'Теги интересов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Путеводитель', 'verbose_name_plural': 'Путеводители'},
        ),
        migrations.AddField(
            model_name='guide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='tours.attraction', verbose_name='Избранная достопримечательность'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='tours.destination', verbose_name='Избранное направление'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='excursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='tours.excursion', verbose_name='Избранная экскурсия'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='tours.hotel', verbose_name='Избранный отель'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'excursion'), ('user', 'hotel'), ('user', 'destination'), ('user', 'attraction')},
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(check=models.Q(('destination__isnull', False), ('hotel__isnull', False), ('attraction__isnull', False), ('excursion__isnull', False), _connector='OR'), name='at_least_one_favorite_item'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='excursions', to='tours.interesttag', verbose_name='Теги интересов'),
        ),
    ]
