# Generated by Django 4.2.6 on 2025-04-18 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0004_interesttag_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Image')),
                ('accommodation_preferences', models.CharField(blank=True, max_length=20, null=True, verbose_name='Accommodation Preferences')),
                ('preferred_currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Preferred Currency')),
                ('preferred_language', models.CharField(blank=True, max_length=2, null=True, verbose_name='Preferred Language')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('promotional_emails', models.BooleanField(default=True, verbose_name='Promotional Emails')),
                ('booking_reminders', models.BooleanField(default=True, verbose_name='Booking Reminders')),
                ('travel_tips', models.BooleanField(default=True, verbose_name='Travel Tips')),
                ('price_alerts', models.BooleanField(default=True, verbose_name='Price Alerts')),
                ('preferred_destinations', models.ManyToManyField(blank=True, related_name='profiles', to='tours.destination', verbose_name='Preferred Destinations')),
                ('travel_interests', models.ManyToManyField(blank=True, related_name='profiles', to='tours.interesttag', verbose_name='Travel Interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
